name: Deploy Prod

on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types: [completed]

jobs:
  deploy:
    name: Deploy to Production (port 80)
    runs-on: self-hosted
    environment: production
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.event.workflow_run.head_repository.owner.login }} --password-stdin

      - name: Deploy
        run: |
          cd /home/toki/Desktop/repos/devops-autoshop
          git pull origin main
          REGISTRY=ghcr.io/${{ github.event.workflow_run.head_repository.owner.login }} \
          IMAGE_TAG=${{ github.event.workflow_run.head_sha }} \
          bash scripts/deploy.sh prod

      - name: Docker logout
        if: always()
        run: docker logout ghcr.io
