name: Deploy Dev

on:
  workflow_run:
    workflows: ["CI"]
    branches: [develop]
    types: [completed]

jobs:
  deploy:
    name: Deploy to Dev (port 8080)
    runs-on: self-hosted
    environment: development
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout develop
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.event.workflow_run.head_repository.owner.login }} --password-stdin

      - name: Deploy
        run: |
          cd /home/toki/Desktop/repos/devops-autoshop
          git pull origin develop
          REGISTRY=ghcr.io/${{ github.event.workflow_run.head_repository.owner.login }} \
          IMAGE_TAG=${{ github.event.workflow_run.head_sha }} \
          bash scripts/deploy.sh dev

      - name: Docker logout
        if: always()
        run: docker logout ghcr.io
